- name: Configure PHP-FPM
  template:
    src: www.conf.jinja2
    dest: /etc/php-fpm.d/www.conf

- name: Restart PHP-FPM
  service:
    name: php-fpm
    state: restarted
    enabled: yes

- name: Create extra Dir
  file:
    path: /etc/nginx/extra
    state: directory

- name: Support PHP
  copy:
    src: nginx-php.conf
    dest: /etc/nginx/extra/php.conf

- name: Copy Default Vhost config
  copy: 
    src: nginx-default-php.conf
    dest: /etc/nginx/conf.d/default.conf

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
